apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-dashboard
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-dashboard
  template:
    metadata:
      labels:
        app: student-dashboard
    spec:
      containers:
        - name: student-dashboard
          image: ${DOCKER_IMAGE}
          ports:
            - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: student-dashboard-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: student-dashboard
  ports:
    - port: 80
      targetPort: 5050
  type: NodePort
